# -*- coding: utf-8 -*-
"""end,acc

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pXsZS11wynSgDjl2NQdqVkenAaRJw-w7
"""

class Accuse:
    def __init__(self, options, next_scene_variables, next_scene_map, image, image_xy, dialogue):
        # self.description = description
        self.options = options
        self.next_scene_variables = next_scene_variables
        self.next_scene_map = next_scene_map
        self.image = image
        self.image_xy = image_xy
        self.selected_option = 0
        self.dialogue = dialogue

    def draw(self):
        # description_font = pygame.font.Font(None, 28)
        option_font = pygame.font.Font(None, 24)
        window.fill(WINDOW_COLOR)
        window.blit(self.image, self.image_xy)

        text = 'Whom will you Accuse?'  # for inventory box
        font = pygame.font.Font(None, 30)
        text_render = font.render(text, True, (33, 38, 46))
        text_x = 222
        text_y = 105
        window.blit(text_render, (text_x, text_y))

        option_y = HEIGHT - 370
        for i, option in enumerate(self.options):  # enumerate done
            option_text = option_font.render(option, True, OPTION_COLOR)
            option_rect = option_text.get_rect(left=180, top=option_y)

            # Draw a highlight around the selected option
            if i == self.selected_option:
                pygame.draw.rect(window, CREME, option_rect, 100)
            window.blit(option_text, option_rect)

            option_y += 28

    def update_selection(self, direction):
        self.selected_option += direction
        if self.selected_option < 0:
            self.selected_option = len(self.options) - 1
        elif self.selected_option >= len(self.options):
            self.selected_option = 0


class GameEnd:
    def __init__(self, text, options, image, image_xy, dialogue):
        self.text = text
        self.options = options
        self.image = image
        self.image_xy = image_xy
        self.dialogue = dialogue
        self.selected_option = 0

    def draw(self):
        # Set up fonts
        option_font = pygame.font.Font(None, 27)
        end_font = pygame.font.SysFont("Georgia", 20)

        # Set up background color

        window.fill(INVENTORY_ITEMS_COLOR)
        window.blit(self.image, (0, 0))

        text = 'GAME END - Case Summary'  # for inventory box
        font = pygame.font.Font(None, 30)
        text_render = font.render(text, True, (33, 38, 46))
        text_x = 50
        text_y = 50
        window.blit(text_render, (text_x, text_y))

        end_lines = textwrap.wrap(self.text, 78)
        y = 80
        for line in end_lines:
            end_text = end_font.render(line, True, END_COLOR)
            end_rect = end_text.get_rect(left=50, top=y)
            window.blit(end_text, end_rect)
            y += 24

        option_y = HEIGHT - 70
        for i, option in enumerate(self.options):  # enumerate done
            option_text = option_font.render(option, True, OPTION_COLOR)
            option_rect = option_text.get_rect(left=380, top=option_y)

            # Draw a highlight around the selected option
            if i == self.selected_option:
                pygame.draw.rect(window, CREME, option_rect, 100)
            window.blit(option_text, option_rect)

            option_y += 28

    def update_selection(self, direction):
        self.selected_option += direction
        if self.selected_option < 0:
            self.selected_option = len(self.options) - 1
        elif self.selected_option >= len(self.options):
            self.selected_option = 0




Sam_end = GameEnd(
    "Sam is not the culprit",
    ["Restart", "Quit"],
    pygame.image.load(
        "C:/Users/advaith\Pictures\Saved Pictures\Pics/1237768.jpg"),
    (0, 0),
    [None, None])

Luke_end = GameEnd(
    "Luke is not the culprit",
    ["Restart", "Quit"],
    pygame.image.load(
        "C:/Users/advaith\Pictures\Saved Pictures\Pics/1237768.jpg"),
    (0, 0),
    [None, None])

Wolf_end = GameEnd(
    "Wolf is not the culprit",
    ["Restart", "Quit"],
    pygame.image.load(
        "C:/Users/advaith\Pictures\Saved Pictures\Pics/1237768.jpg"),
    (0, 0),
    [None, None])

Peter_end = GameEnd(
    "The murderer was Peter Jespers, who wanted revenge for being put out of work by the victim.                       "
    "                                                 Industrialist Matthew Killian was drugged and thrown from the top"
    " of a moving train by his former employee, "
    "Peter Jespers! Put out of work by the mechanization of Killian's factory, Peter found employment as a humble "
    "train steward. However, one evening Peter realized that Killian was in his very train (prior to this journey "
    "Peter had never seen Killian, but now recognized him from a recent newspaper article). Peter, knowing that "
    "frequent passenger Vivian often swindled wealthy fellow passengers, waited until she lured Killian to her "
    "compartment. He cunningly arranged for her to be called away by means of an anonymous note. Peter then used his "
    "considerable strength to lift the drugged magnate and drag him to the top of the train, whence he threw him to "
    "his death at midnight! Killian's rival, Angus Wolf, had hoped to get Killian so inebriated as to prevent him "
    "from participating in a business meeting on the following day, but Wolf himself fell afoul of the drugged brandy "
    "and slept through the entire episode! As for Peter the murderer... perhaps he meted out justice, in turn he will "
    "not meet justice himself! – Henry Raymond ",
    ["Restart", "Quit"],
    pygame.image.load(
        "C:/Users/advaith\Pictures\Saved Pictures\Pics/1237768.jpg"),
    (0, 0),
    [None, None])

Vivian_end = GameEnd(
    "Vivian is not the culprit",
    ["Restart", "Quit"],
    pygame.image.load(
        "C:/Users/advaith\Pictures\Saved Pictures\Pics/1237768.jpg"),
    (0, 0),
    [None, None])

Ryan_end = GameEnd(
    "Ryan is not the culprit",
    ["Restart", "Quit"],
    pygame.image.load(
        "C:/Users/advaith\Pictures\Saved Pictures\Pics/1237768.jpg"),
    (0, 0),
    [None, None]

)
scene_accuse = Accuse(["is it Ryan", "is it  Vivian", "is it Peter", "is it Mr.wolf", "is it luke",
                       "is it Sam", "Return"],
                      ["Ryan", "Vivian", "Peter", "Wolf", "Luke", "Sam", "Go back"],
                      {
                          "Ryan": Ryan_end,
                          "Vivian": Vivian_end,
                          "Peter": Peter_end,
                          "Wolf": Wolf_end,
                          "Luke": Luke_end,
                          "Sam": Sam_end,
                          "Go back": None
                      },
                      pygame.image.load(
                          "C:/Users/advaith\Pictures\Saved Pictures\Pics/1237768.jpg"),
                      (0, 0),
                      [None, None, None, None, None, None, None])