# -*- coding: utf-8 -*-
"""prol

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VjY9yCzUmVTEwhWppfBi8Ri7Pd_8GMrm
"""

class Prologue:
    def __init__(self, text, image, enter):
        self.text = text
        self.image = image
        self.enter = enter

    def draw(self):
        # Set up fonts
        enter_font = pygame.font.Font(None, 27)
        prologue_font = pygame.font.SysFont("Georgia", 20)

        # Set up background color

        window.fill(INVENTORY_ITEMS_COLOR)
        window.blit(self.image, (-300, 0))

        # Draw the prologue text
        enter_text = enter_font.render(self.enter, True, PROLOGUE_COLOR)
        enter_rect = enter_text.get_rect(left=500, top=560)
        pygame.draw.rect(window, CREME, enter_rect, 10)
        window.blit(enter_text, enter_rect)

        text = 'PROLOGUE'  # for inventory box
        font = pygame.font.Font(None, 30)
        text_render = font.render(text, True, (33, 38, 46))
        text_x = 50
        text_y = 50
        window.blit(text_render, (text_x, text_y))

        prologue_lines = textwrap.wrap(self.text, 78)
        y = 80
        for line in prologue_lines:
            prologue_text = prologue_font.render(line, True, (0, 0, 0))
            prologue_rect = prologue_text.get_rect(left=50, top=y)
            window.blit(prologue_text, prologue_rect)
            y += 24


prologue2 = Prologue("London, 1868, A city cloaked in a fog of coal smoke and secrets, where gas lamps "
                     "flickered, casting eerie shadows on cobblestone streets. As you make your way along a dimly lit"
                     " road, the sound of your boots echoed against the damp stones and the surrounding buildings,"
                     " blending with the distant sound of traffic and muffled conversations. The thick mist embraced"
                     " the city, veiling its mysteries, but your trained eye could discern the subtle signs"
                     "of trouble. And trouble, it seemed, awaited you just ahead. As you were thinking, you encounter a"
                     " chap working at the road. The chap screams:                                       "
                     "                                Hey! Someone help! Some tramp found something down there!",
                     pygame.image.load(
                         r"C:\Users\advaith\Pictures\Saved Pictures\Pics\600965.jpg"),
                     "press 'Enter' to continue.")
prologue = Prologue("Looks like foul play! You rush to the scene. In the dimly lit streets of the city, "
                    "shadows danced along the crumbling"
                    "facades of buildings. The air was thick with a palpable tension, as if the very atmosphere held "
                    "secrets that were itching to be unraveled. It was a city that had seen its fair share of crimes, "
                    "a breeding ground for both the desperate and the cunning. You instantly walk down the road "
                    "under to the arches of an ancient bridge.      There, lying on the ground, was a lifeless body - a "
                    "gentleman whose face bore the pallor of death and whose finely tailored clothing contrasted "
                    "starkly with the squalor of the surroundings. The mist draped him like a mourning shroud, "
                    "while the flickering light of a gas lamp cast an eerie glow upon his still form.",
                    pygame.image.load(
                        r"C:\Users\advaith\Pictures\Saved Pictures\Pics\assassins_creed_syndicate_london_art-7.png"),
                    "-press 'Enter' to start story.")

# Flag to control whether the menu is active

prologue_active = True
prologue2_active = True
# accuse_active = False

def handle_Coat_Tramp_selection(option):
    if option == 0:
        if "Talk about the coat" not in initial_scene2.options:
            initial_scene2.options.insert(-1, "Talk about the coat")
            initial_scene2.next_scene_variables.insert(-1, 99)
            initial_scene2.dialogue.insert(-1,
                                           "Vagrant: A nice, warm coat like that on a dead man, what do you expect? I "
                                           "snatched it before somebody else come along to nick it.")


def handle_Watch_Tramp_selection(option):
    if option == 3:
        if "What about Midnight train" not in initial_scene2.options:
            initial_scene2.options.insert(-1, "What about Midnight train")
            initial_scene2.next_scene_variables.insert(-1, 89)
            initial_scene2.dialogue.insert(-1,
                                           "Vagrant: The midnight train? That must be the 616. Stops in the station "
                                           "down the road. If you hurry, it might still be there.")


def handle_Station_selection(option):
    if option == 89:
        if "Go to the train station" not in initial_scene2.options:
            initial_scene2.options.insert(-1, "Go to the train station")
            initial_scene2.next_scene_variables.insert(-1, "next_scene")
            initial_scene2.next_scene_map["next_scene"] = initial_scene3



def handle_Peter_Ryan_selection(option):
    if option == 2:
        if "Enquire about Peter" not in Ryan.options:
            Ryan.options.insert(-1, "Enquire about Peter")
            Ryan.next_scene_variables.insert(-1, 99)
            Ryan.dialogue.insert(-1,
                                 "Peter? Nice bloke. Came here after being sacked from a foundry a few months ago. I'll"
                                 " tell you, he looked white as a ghost after he served the businessmen.")


def handle_pills_Ryan_selection(option):
    if option == 4:
        if "Ask about the pills" not in Ryan.options:
            Ryan.options.insert(-1, "Ask about the pills")
            Ryan.next_scene_variables.insert(-1, 99)
            Ryan.dialogue.insert(-1,
                                 "Oh, er - well, it's a noisy train. Plenty of passengers have trouble getting to "
                                 "sleep, So i keep a sedative here behind the bar .yeah?")


def handle_Vivian_Peter_selection(option):
    if option == 2:
        if "Who is Vivian?" not in Peter.options:
            Peter.options.insert(-1, "Who is Vivian?")
            Peter.next_scene_variables.insert(-1, 99)
            Peter.dialogue.insert(-1,
                                  "She rides the train often. She's very friendly with the other passengers.")


def handle_Vivian_Ryan_selection(option):
    if option == 0:
        if "Ask about Vivian" not in Ryan.options:
            Ryan.options.insert(-1, "Ask about Vivian")
            Ryan.next_scene_variables.insert(-1, 99)
            Ryan.dialogue.insert(-1,
                                 "She's a frequent passenger, that one. Hangs about with the wealthier sort. Likes "
                                 "to 'entertain' 'em, if you take my meanin'.")


def handle_Scheme_Ryan_selection(option):
    if option == 1:
        if "Ask about Scheme" not in Ryan.options:
            Ryan.options.insert(-1, "Ask about Scheme")
            Ryan.next_scene_variables.insert(-1, 99)
            Ryan.dialogue.insert(-1,
                                 "Yeah, I help Vivian fleece the dupes. I slipped a pill in the wine for the table. "
                                 "Both gents got sleepy, but Vivian picked the richest one.")


def handle_Vivian_Luke_selection(option):
    if option == 2:
        if "Ask about Vivian" not in Luke.options:
            Luke.options.insert(-1, "Ask about Vivian")
            Luke.next_scene_variables.insert(-1, 99)
            Luke.dialogue.insert(-1,
                                 "That one! Clever little minx. She and the barman got a little scam goin'. I think "
                                 "everyone on staff knows about it.")


def handle_Peter_Luke_selection(option):
    if option == 2:
        if "Enquire about Peter" not in Luke.options:
            Luke.options.insert(-1, "Enquire about Peter")
            Luke.next_scene_variables.insert(-1, 99)
            Luke.dialogue.insert(-1,
                                 "Luke : Oh, Peter worked with me at the foundry. He's a very strong bloke. I got me "
                                 "arm mangled in one of the damned machines they put in. Then Killian sacked the "
                                 "whole crew. Peter, he helped me get hired as train staff.", )

def handle_Valet_Wolf_selection(option):
    if option == 4:
        if 'Enquire about the valet' not in Wolf.options:
            Wolf.options.insert(-1, 'Enquire about the valet')
            Wolf.next_scene_variables.insert(-1, 99)
            Wolf.dialogue.insert(-1,
                                 "Angus Wolf: Sam? He's a trusted valet. He's terrifically strong,which makes him useful in many situations.")

def handle_Vivian_Wolf_selection(option):
    if option == 2:
        if "Enquire about Vivian" not in Wolf.options:
            Wolf.options.insert(-1, "Enquire about Vivian")
            Wolf.next_scene_variables.insert(-1, 99)
            Wolf.dialogue.insert(-1,
                                 "Angus Wolf:You mean the young lady? She and Killian hit it off famously. Embarrassing, "
                                 "really.")


def handle_Note_Vivian_selection(option):
    if option == 3:
        if 'Talk about the note' not in Vivian.options:
            Vivian.options.insert(-1, 'Talk about the note')
            Vivian.next_scene_variables.insert(-1, 99)
            Vivian.dialogue.insert(-1,
                                   "Vivian :Someone slipped a note under my sleeper door a few minutes before "
                                   "midnight. It said I should come to the dining car. I went, but only Ryan and "
                                   "Wolf's man were there and they were both drunk."
                                   )